import numpy as np
import pandas as pd
import scipy
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from tqdm import tqdm
import time

""" Specify path to the TXT file generated by the Hamamatsu acquisition software"""

filepath = r"C:\Users\fernadi1\OneDrive - Idorsia\Desktop\test hamamatsu\tests\RAW\test.txt"


metadata = pd.read_csv(filepath, delimiter='\t', nrows = 6, header = None, index_col= 1)
metadata = metadata.drop(columns=[0])
metadata = metadata[2].to_dict()
original_data_file = metadata['Data File Name :']
adquisition_date = pd.to_datetime(metadata['Date :'])
adquisition_time = pd.to_timedelta(metadata['Time :'])
marker = pd.to_timedelta(metadata['Marker1 :'])

rawdata = pd.read_csv(filepath, delimiter='\t', skiprows = [0,1,2,3,4,5,6,8,9,10])

# selecting raw data
rawdata.rename(columns={'No.': 'Time[ms]'}, inplace=True)

rawdata = rawdata.drop(['Unnamed: 0'], axis=1)
rawdata['Time[min]'] =rawdata['Time[ms]'] / 1000 * (1 / 60)


#Transforming time data into pd.to_timedelta object
rawdata['Time[ms]'] = pd.to_timedelta(rawdata['Time[ms]'], unit = 'ms')
rawdata['Time[min]'] = pd.to_timedelta(rawdata['Time[min]'], unit = 'm')

#Transforming time data into integers
rawdata['Time[min]_int'] = rawdata['Time[min]'] / pd.Timedelta(minutes=1)
markerint = marker / pd.Timedelta(minutes=1)

#subplots with plotly

from plotly.subplots import make_subplots

wells = list(rawdata)[1:-2]
well = 0

fig = make_subplots(
    rows=8, cols=12,
    subplot_titles=(wells))

well = 'B10'
i,j = 1,1

fig.add_trace(go.Scatter(x = rawdata['Time[min]_int'], y=rawdata[well]), row=i, col=j)

for well in wells:
    fig.add_trace(go.Scatter(x=rawdata['Time[min]_int'], y=rawdata[well]), row=j, col=i)
    print(i)
    print(j)

    i += 1
    if i == 13:
        i = 0
        j += 1